apiVersion: v1

kind: Service

metadata:

  name: weather-app

  labels:

    run: weather-app

spec:

  type: NodePort

  ports:

  - port: 80

    targetPort: 5000

    nodePort: 30000

    protocol: TCP

  selector:

    run: weather-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: weather-app
  template:
    metadata:
      labels:
        run: weather-app
    spec:
      containers:
      - name: weather
        image: REPLACE
        ports:
        - containerPort: 5000