apiVersion: v1

kind: Service

metadata:

  name: weather-app

  labels:

    run: weather-app

spec:

  type: NodePort

  ports:

  - port: 80

    targetPort: 5000

    protocol: TCP


  selector:

    run: weather-app

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: weather-app

spec:

  selector:

    matchLabels:

      run: weather-app

  replicas: 2

  template:

    metadata:

      labels:

        run: weather-app

    spec:

      containers:

      - name: weather-app

        image: aldurama/weather:latest

        ports:

        - containerPort: 5000